/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service, device and model health
         * @description Report service health.
         *
         *     ``device.igpu_masked`` asserts that ``HIP_VISIBLE_DEVICES=0`` took effect. A
         *     ``false`` there is a red flag before any demo.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every registered tool
         * @description Return every tool, available or not.
         *
         *     Entries with ``available: false`` must be rendered as disabled rather than
         *     hidden — the registry being real, and honest about what is not loaded yet,
         *     is part of the story.
         */
        get: operations["registry_v1_registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check whether the uploaded images can be analysed together
         * @description Run ingestion and compatibility checks only — no tools, no GPU.
         *
         *     Call this on file select, before the user types: ``supported_tasks`` tells the
         *     UI which questions to offer.
         */
        post: operations["validate_v1_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer a question about one or two images
         * @description Run the full pipeline and return the answer, its evidence and the trace.
         *
         *     A tool failure never produces a 5xx: it produces ``200`` with a ``DEGRADED``
         *     or ``SKIPPED`` execution, a populated ``errors[]`` and a reduced confidence.
         *     The single exception is a step the policy entry declares non-optional — only
         *     the renderer today — because without rendered views there is no evidence to
         *     reason over at all.
         */
        post: operations["analyze_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue an analysis and watch it stream
         * @description Accept the same body as ``/v1/analyze`` and return immediately.
         *
         *     The returned ``job_id`` *is* the eventual ``trace_id``, so the client can
         *     address the trace before the pipeline has produced it.
         */
        post: operations["create_job_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll one job's progress
         * @description Return the job's current stage, progress and — once finished — its result.
         */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent progress events for one job
         * @description Stream the job's events, replaying everything that already happened.
         *
         *     A subscriber that connects late — the normal case, since the client needs the
         *     ``job_id`` from the 202 first — receives the buffered history before the live
         *     tail, so the DAG can always be drawn from the ``plan`` event.
         */
        get: operations["job_events_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{trace_id}/{artifact_id}.{ext}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one artifact's raw bytes
         * @description Serve one artifact with immutable caching and conditional-request support.
         */
        get: operations["get_artifact_v1_artifacts__trace_id___artifact_id___ext__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one stored audit trace
         * @description Return the full audit trace for *trace_id*.
         */
        get: operations["get_trace_v1_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyzeResponse
         * @description ``POST /v1/analyze`` 200 body.
         *
         *     ``compatibility`` and ``resolved_task`` are duplicated at the top level so the
         *     UI can render them without walking into the trace.
         */
        AnalyzeResponse: {
            /** Trace Id */
            trace_id: string;
            answer: components["schemas"]["Answer"];
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactRef"][];
            confidence: components["schemas"]["Confidence"];
            compatibility: components["schemas"]["CompatibilityReport"];
            resolved_task: components["schemas"]["ResolvedTask"];
            /** @description None when options.include_trace is false. */
            trace?: components["schemas"]["AuditTrace"] | null;
        };
        /**
         * Answer
         * @description The synthesised natural-language answer plus its honesty signals.
         */
        Answer: {
            /** Text */
            text: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Uncited Numeric Spans
             * @description Numbers the CitationValidator could not resolve. Non-empty is a visible honesty signal — the frontend must render it.
             */
            uncited_numeric_spans?: string[];
            /**
             * Generator
             * @description e.g. 'vlm_change_vqa@1.0.0+adapter:sq-lora-v3'.
             */
            generator: string;
            /**
             * Template Fallback
             * @description True when a deterministic template wrote the text.
             * @default false
             */
            template_fallback: boolean;
        };
        /**
         * ApiError
         * @description The error payload (API_CONTRACT §6).
         *
         *     ``message`` and ``hint`` are user-facing and safe to display verbatim: never
         *     leak file paths or stack traces into either.
         */
        ApiError: {
            /** Code */
            code: string;
            /** Http Status */
            http_status: number;
            /** Message */
            message: string;
            /**
             * Hint
             * @description An actionable next step.
             */
            hint?: string | null;
            /** Ref */
            ref?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * ArtifactGeo
         * @description Georeferencing of a raster artifact.
         */
        ArtifactGeo: {
            /** Crs */
            crs: string;
            /** Transform */
            transform: number[];
        };
        /**
         * ArtifactRef
         * @description A piece of evidence the pipeline produced. Immutable and cacheable forever.
         */
        ArtifactRef: {
            /**
             * Id
             * @description art_0, art_1, ... stable within a trace.
             */
            id: string;
            type: components["schemas"]["ArtifactType"];
            /**
             * Mime
             * @description image/png, image/tiff, application/geo+json, application/json.
             */
            mime: string;
            /**
             * Label
             * @description Display name, e.g. 'Change mask (binary)'.
             */
            label: string;
            /**
             * Url
             * @description None for SCALARS/TEXT.
             */
            url?: string | null;
            /** Geotiff Url */
            geotiff_url?: string | null;
            /** Geojson Url */
            geojson_url?: string | null;
            /** @description None when the artifact is not georeferenced. */
            geo?: components["schemas"]["ArtifactGeo"] | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /**
             * Stats
             * @description Artifact-type specific.
             */
            stats?: {
                [key: string]: unknown;
            } | null;
            /**
             * Inline
             * @description Payload for SCALARS/BBOX_SET/TEXT — avoids a second round trip.
             */
            inline?: {
                [key: string]: unknown;
            } | null;
            /**
             * Produced By Step
             * @description Index into plan.steps.
             */
            produced_by_step: number;
        };
        /**
         * ArtifactType
         * @description Kind of evidence produced by a tool (API_CONTRACT §2.5).
         * @enum {string}
         */
        ArtifactType: "RENDERED_VIEW" | "CHANGE_MASK" | "SEGMENTATION" | "BBOX_SET" | "HEATMAP" | "OVERLAY_PNG" | "GEOJSON" | "SCALARS" | "TEXT";
        /**
         * AuditTrace
         * @description The full, replayable record of one analysis — the requirement-5 deliverable.
         *
         *     Top-level key order is frozen by API_CONTRACT §3.11 and is preserved here.
         */
        AuditTrace: {
            /**
             * Trace Id
             * @description 32-char lowercase hex.
             */
            trace_id: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            query: components["schemas"]["QuerySpec"];
            resolved_task: components["schemas"]["ResolvedTask"];
            /** Inputs */
            inputs: components["schemas"]["InputManifest"][];
            compatibility: components["schemas"]["CompatibilityReport"];
            plan: components["schemas"]["Plan"];
            /** Executions */
            executions: components["schemas"]["Execution"][];
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactRef"][];
            /**
             * Fact Sheet
             * @description Keys are namespaced '<tool>.<scalar>'.
             */
            fact_sheet?: {
                [key: string]: number | string;
            };
            answer: components["schemas"]["Answer"];
            confidence: components["schemas"]["Confidence"];
            /** Warnings */
            warnings?: components["schemas"]["WarningItem"][];
            /** Errors */
            errors?: components["schemas"]["ErrorItem"][];
        };
        /** Body_analyze_v1_analyze_post */
        Body_analyze_v1_analyze_post: {
            /**
             * Images
             * @description 1-2 files. GeoTIFF preferred; PNG/JPEG accepted.
             */
            images: string[];
            /**
             * Query
             * @description 1-1000 chars, UTF-8.
             */
            query: string;
            /**
             * Options
             * @description JSON, see AnalyzeOptions.
             */
            options?: string | null;
        };
        /** Body_create_job_v1_jobs_post */
        Body_create_job_v1_jobs_post: {
            /**
             * Images
             * @description 1-2 files. GeoTIFF preferred; PNG/JPEG accepted.
             */
            images: string[];
            /**
             * Query
             * @description 1-1000 chars, UTF-8.
             */
            query: string;
            /**
             * Options
             * @description JSON, see AnalyzeOptions.
             */
            options?: string | null;
        };
        /** Body_validate_v1_validate_post */
        Body_validate_v1_validate_post: {
            /**
             * Images
             * @description 1-2 files. GeoTIFF preferred; PNG/JPEG accepted.
             */
            images: string[];
            /**
             * Options
             * @description JSON; only pair_type_hint and roles are honoured here.
             */
            options?: string | null;
        };
        /**
         * CheckName
         * @description Identity of a compatibility check (API_CONTRACT §2.6).
         * @enum {string}
         */
        CheckName: "crs_match" | "bounds_overlap_iou" | "gsd_ratio" | "coregistration_offset_px" | "band_sufficiency" | "modality_distinct" | "temporal_ordering" | "georeference_present" | "size_ratio" | "nodata_extent";
        /**
         * CheckResult
         * @description One compatibility check, including the ones that were skipped.
         */
        CheckResult: {
            name: components["schemas"]["CheckName"];
            status: components["schemas"]["CheckStatus"];
            /**
             * Value
             * @description Measured value.
             */
            value?: number | string | null;
            /**
             * Threshold
             * @description Human-readable rule, e.g. 'iou >= 0.80'.
             */
            threshold?: string | null;
            /**
             * Detail
             * @description One sentence, safe to display verbatim.
             */
            detail: string;
        };
        /**
         * CheckStatus
         * @description Outcome of one compatibility check (API_CONTRACT §2.7).
         * @enum {string}
         */
        CheckStatus: "PASS" | "WARN" | "FAIL" | "SKIP";
        /**
         * Citation
         * @description Binds one claim in the answer text to one measured scalar.
         */
        Citation: {
            /**
             * Claim
             * @description The exact span of answer text this supports.
             */
            claim: string;
            /**
             * Source
             * @description Grammar: 'step:{n}/scalars.{dotted.path}'; join two with '|'.
             * @example step:2/scalars.changed_area_pct
             */
            source: string;
            /**
             * Value
             * @description The cited value, as measured.
             */
            value: number | string;
        };
        /**
         * CommonGrid
         * @description The grid both images were resampled onto for pairwise analysis.
         */
        CommonGrid: {
            /** Crs */
            crs: string;
            /** Transform */
            transform: number[];
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Gsd M */
            gsd_m: number;
            resampling: components["schemas"]["Resampling"];
        };
        /**
         * CompatibilityReport
         * @description Whether the inputs can be analysed together, and what it cost to get there.
         */
        CompatibilityReport: {
            pair_type: components["schemas"]["PairType"];
            pair_type_source: components["schemas"]["PairTypeSource"];
            /**
             * Checks
             * @description Every applicable check, including SKIP.
             */
            checks: components["schemas"]["CheckResult"][];
            /** @description any FAIL -> FAIL; else any WARN -> PASS_WITH_WARNINGS; else PASS. */
            overall: components["schemas"]["Overall"];
            /**
             * Actions Taken
             * @description e.g. 'reprojected img_1 EPSG:4326->EPSG:32643 (bilinear)'.
             */
            actions_taken?: string[];
            /** @description None for SINGLE and for FAIL. */
            common_grid?: components["schemas"]["CommonGrid"] | null;
        };
        /**
         * Confidence
         * @description Overall confidence and the components it was derived from.
         */
        Confidence: {
            /** Overall */
            overall: number;
            /**
             * Method
             * @description e.g. 'weighted_tool_agreement_v1'.
             */
            method: string;
            /** Components */
            components?: {
                [key: string]: number;
            };
            /**
             * Caps Applied
             * @description Names of any rule that clamped `overall`.
             */
            caps_applied?: string[];
        };
        /**
         * Device
         * @description Compute placement (API_CONTRACT §2.10).
         * @enum {string}
         */
        Device: "rocm:0" | "cpu" | "auto";
        /**
         * DeviceInfo
         * @description Accelerator state, as reported by the ROCm runtime.
         */
        DeviceInfo: {
            /**
             * Backend
             * @description 'rocm' | 'cpu'.
             */
            backend: string;
            /** Name */
            name: string;
            /** Hip Visible Devices */
            hip_visible_devices?: string | null;
            /** Vram Total Mb */
            vram_total_mb?: number | null;
            /** Vram Used Mb */
            vram_used_mb?: number | null;
            /**
             * Igpu Masked
             * @description Asserts HIP_VISIBLE_DEVICES=0 took effect. False is a red flag before a demo.
             */
            igpu_masked: boolean;
        };
        /**
         * ErrorItem
         * @description A failure that did not prevent a partial result.
         */
        ErrorItem: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Step */
            step?: number | null;
        };
        /**
         * Execution
         * @description The record of actually running one :class:`PlanStep` — the audit payload.
         */
        Execution: {
            /**
             * Step
             * @description Matches PlanStep.step.
             */
            step: number;
            /** Tool */
            tool: string;
            /** Version */
            version: string;
            status: components["schemas"]["ToolStatus"];
            device_used: components["schemas"]["Device"];
            /** Duration Ms */
            duration_ms: number;
            /**
             * Params
             * @description Exact effective parameters — the auditability payload.
             */
            params?: {
                [key: string]: unknown;
            };
            /** Input Refs */
            input_refs?: string[];
            /** Output Refs */
            output_refs?: string[];
            /**
             * Scalars
             * @description Merged into fact_sheet under this tool's namespace.
             */
            scalars?: {
                [key: string]: number | string;
            };
            /** Confidence */
            confidence: number;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /**
             * Fallback Of
             * @description Set when this execution replaced a failed tool.
             */
            fallback_of?: string | null;
            /** Error */
            error?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description ``GET /v1/health`` 200 body (API_CONTRACT §4.9).
         */
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /** Version */
            version: string;
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            device: components["schemas"]["DeviceInfo"];
            /** Models */
            models?: components["schemas"]["ModelInfo"][];
            /** Tools Available */
            tools_available: number;
            /** Tools Total */
            tools_total: number;
        };
        /**
         * HealthStatus
         * @description Service-level health verdict (API_CONTRACT §4.9).
         * @enum {string}
         */
        HealthStatus: "ok" | "degraded";
        /**
         * ImageRole
         * @description Role an image plays within its pair (API_CONTRACT §2.4).
         * @enum {string}
         */
        ImageRole: "single" | "pre" | "post" | "optical" | "sar";
        /**
         * InputContract
         * @description What a tool is willing to accept — the basis of capability matching.
         */
        InputContract: {
            /** Pair Types */
            pair_types: components["schemas"]["PairType"][];
            /** Modalities */
            modalities: components["schemas"]["Modality"][];
            /** Min Images */
            min_images: number;
            /** Max Images */
            max_images: number;
            /**
             * Required Bands
             * @description Logical band names, resolved per-sensor.
             */
            required_bands?: string[];
            /** Optional Bands */
            optional_bands?: string[];
            /**
             * Gsd Range M
             * @description [min_gsd_m, max_gsd_m].
             */
            gsd_range_m?: number[] | null;
            /** Min Size Px */
            min_size_px?: number | null;
            /** Max Size Px */
            max_size_px?: number | null;
            /**
             * Requires Georeference
             * @default false
             */
            requires_georeference: boolean;
        };
        /**
         * InputManifest
         * @description Everything the ingestion layer learned about one uploaded image.
         *
         *     A field that is *inapplicable* is ``None``. A field that is *unknown* is
         *     ``None`` **and** carries an entry in :attr:`warnings`.
         */
        InputManifest: {
            /**
             * Id
             * @description Stable within a trace: img_0, img_1, ... in upload order.
             */
            id: string;
            /** @description Server-assigned unless overridden via options.roles. */
            role?: components["schemas"]["ImageRole"] | null;
            /**
             * Filename
             * @description Original client filename, sanitised.
             */
            filename: string;
            /**
             * Sha256
             * @description Of the raw bytes.
             */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Driver
             * @description rasterio driver: GTiff, PNG, JPEG.
             */
            driver: string;
            modality: components["schemas"]["Modality"];
            /** Modality Confidence */
            modality_confidence: number;
            /**
             * Sensor Guess
             * @description e.g. 'Sentinel-2 L2A', 'Sentinel-1 GRD', 'Cartosat-2S'.
             */
            sensor_guess?: string | null;
            /**
             * Crs
             * @description e.g. 'EPSG:32643'; None for non-georeferenced input.
             */
            crs?: string | null;
            /**
             * Transform
             * @description rasterio/GDAL affine 6-tuple [a, b, c, d, e, f].
             */
            transform?: number[] | null;
            /**
             * Bounds Native
             * @description [minx, miny, maxx, maxy] in the raster's own CRS.
             */
            bounds_native?: number[] | null;
            /**
             * Bounds Wgs84
             * @description [min_lon, min_lat, max_lon, max_lat], lon first, EPSG:4326.
             */
            bounds_wgs84?: number[] | null;
            /**
             * Gsd M
             * @description Ground sample distance, metres.
             */
            gsd_m?: number | null;
            /**
             * Width
             * @description Pixels.
             */
            width: number;
            /**
             * Height
             * @description Pixels.
             */
            height: number;
            /** Band Count */
            band_count: number;
            /**
             * Dtype
             * @description uint8, uint16, int16, float32.
             */
            dtype: string;
            /**
             * Band Names
             * @description ["B02","B03",...] or ["VV","VH"].
             */
            band_names?: string[] | null;
            /** Nodata Pct */
            nodata_pct: number;
            /**
             * Acquisition Time
             * @description From TIFF/GDAL metadata when present.
             */
            acquisition_time?: string | null;
            /**
             * Is Georeferenced
             * @description crs is not None and transform is not None.
             */
            is_georeferenced: boolean;
            /**
             * Warnings
             * @description May be empty, never None.
             */
            warnings?: string[];
        };
        /**
         * JobAccepted
         * @description ``POST /v1/jobs`` 202 body (API_CONTRACT §4.2).
         *
         *     ``job_id`` *is* the eventual ``trace_id``: the id is minted before the
         *     pipeline runs, so a client can address the trace before it exists.
         */
        JobAccepted: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
            /**
             * Poll Url
             * @description e.g. '/v1/jobs/b3f1...'.
             */
            poll_url: string;
            /**
             * Events Url
             * @description SSE endpoint, e.g. '/v1/jobs/b3f1.../events'.
             */
            events_url: string;
        };
        /**
         * JobStatusResponse
         * @description ``GET /v1/jobs/{job_id}`` 200 body (API_CONTRACT §4.3).
         *
         *     ``result`` is populated only once ``status`` is ``succeeded``, ``error``
         *     only once it is ``failed``; they are mutually exclusive, mirroring the
         *     ``done``/``error`` terminal SSE events.
         */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /**
             * Stage
             * @description queued|ingesting|validating|rendering|planning|executing|aggregating|done.
             */
            stage: string;
            /** Step */
            step: number;
            /** Total Steps */
            total_steps: number;
            /** Pct */
            pct: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            result?: components["schemas"]["AnalyzeResponse"] | null;
            error?: components["schemas"]["ApiError"] | null;
        };
        /**
         * Modality
         * @description Sensing modality of a single input (API_CONTRACT §2.3).
         * @enum {string}
         */
        Modality: "optical" | "sar" | "panchromatic" | "unknown";
        /**
         * ModelInfo
         * @description One loadable model and its adapter.
         */
        ModelInfo: {
            /** Name */
            name: string;
            /**
             * Backend
             * @description 'hf' | 'llamacpp'.
             */
            backend: string;
            /** Loaded */
            loaded: boolean;
            /** Adapter */
            adapter?: string | null;
        };
        /**
         * Overall
         * @description Aggregate compatibility verdict (API_CONTRACT §2.7).
         *
         *     Derivation: any FAIL -> FAIL; else any WARN -> PASS_WITH_WARNINGS; else PASS.
         * @enum {string}
         */
        Overall: "PASS" | "PASS_WITH_WARNINGS" | "FAIL";
        /**
         * PairType
         * @description Relationship between the uploaded images (API_CONTRACT §2.2).
         * @enum {string}
         */
        PairType: "SINGLE" | "CROSS_MODAL" | "BI_TEMPORAL" | "INCOMPATIBLE";
        /**
         * PairTypeSource
         * @description How ``CompatibilityReport.pair_type`` was decided (API_CONTRACT §3.3).
         * @enum {string}
         */
        PairTypeSource: "metadata" | "heuristic" | "user_declared";
        /**
         * Plan
         * @description The tool DAG chosen for this query.
         */
        Plan: {
            /**
             * Planner
             * @description e.g. 'policy_table_v1'.
             */
            planner: string;
            /**
             * Policy Key
             * @description e.g. 'CHANGE_VQA|BI_TEMPORAL|optical'.
             */
            policy_key: string;
            /** Steps */
            steps?: components["schemas"]["PlanStep"][];
        };
        /**
         * PlanStep
         * @description One node of the execution DAG, in topological order.
         */
        PlanStep: {
            /**
             * Step
             * @description 1-indexed position in topological order.
             */
            step: number;
            /** Tool */
            tool: string;
            /** Depends On */
            depends_on?: number[];
            /**
             * Input Refs
             * @description img_* and/or art_* references.
             */
            input_refs: string[];
            /**
             * Reason
             * @description e.g. 'policy_table:CHANGE_VQA|BI_TEMPORAL|optical'.
             */
            reason: string;
        };
        /**
         * QuerySpec
         * @description The user's question, as received and as normalised.
         */
        QuerySpec: {
            /** Raw */
            raw: string;
            /** Normalized */
            normalized: string;
            /**
             * Language
             * @description ISO 639-1.
             * @default en
             */
            language: string;
        };
        /**
         * RegistryResponse
         * @description ``GET /v1/registry`` 200 body (API_CONTRACT §4.8).
         */
        RegistryResponse: {
            /** Registry Version */
            registry_version: string;
            /** Tools */
            tools: components["schemas"]["ToolSpec"][];
            /** Task Types */
            task_types: components["schemas"]["TaskType"][];
            /** Adapter Version */
            adapter_version?: string | null;
        };
        /**
         * Resampling
         * @description Resampling kernel used to build the common grid (API_CONTRACT §3.3).
         * @enum {string}
         */
        Resampling: "nearest" | "bilinear" | "cubic";
        /**
         * ResolvedTask
         * @description What the query classifier decided the user is asking for.
         */
        ResolvedTask: {
            primary: components["schemas"]["TaskType"];
            /** Secondary */
            secondary?: components["schemas"]["TaskType"][];
            /** Slots */
            slots?: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence: number;
            /**
             * Classifier
             * @description e.g. 'rules_v1+llm_slotfill_v1'.
             */
            classifier: string;
        };
        /**
         * TaskType
         * @description Resolved analysis task (API_CONTRACT §2.1).
         * @enum {string}
         */
        TaskType: "VQA" | "CAPTION" | "GROUNDING" | "SEGMENTATION" | "COUNT" | "SCENE_CLASSIFY" | "CHANGE_VQA" | "CHANGE_CAPTION" | "CHANGE_MAP" | "CROSS_MODAL_VQA" | "CROSS_MODAL_COMPARE" | "UNSUPPORTED";
        /**
         * ToolCategory
         * @description Registry grouping for a tool (API_CONTRACT §2.9).
         * @enum {string}
         */
        ToolCategory: "analysis" | "vlm" | "cv" | "geo" | "fusion";
        /**
         * ToolSpec
         * @description One registry entry, as served by ``GET /v1/registry``.
         */
        ToolSpec: {
            /**
             * Name
             * @description Registry key, snake_case, stable.
             */
            name: string;
            /**
             * Version
             * @description '1.0.0' or '1.0.0+ckpt:9a3f'.
             */
            version: string;
            category: components["schemas"]["ToolCategory"];
            /**
             * Description
             * @description One line, shown in the capabilities panel.
             */
            description: string;
            accepts: components["schemas"]["InputContract"];
            /** Produces */
            produces: components["schemas"]["ArtifactType"][];
            /**
             * Scalars Schema
             * @description JSON Schema of this tool's FactSheet contribution.
             */
            scalars_schema?: {
                [key: string]: unknown;
            };
            device: components["schemas"]["Device"];
            /**
             * Est Ms
             * @description Typical wall time, for the progress bar.
             */
            est_ms: number;
            /**
             * Fallback
             * @description Name of the tool used when this one fails.
             */
            fallback?: string | null;
            /**
             * Available
             * @description Runtime: false when weights/backend are missing.
             */
            available: boolean;
            /** Unavailable Reason */
            unavailable_reason?: string | null;
        };
        /**
         * ToolStatus
         * @description Outcome of a single tool execution (API_CONTRACT §2.8).
         * @enum {string}
         */
        ToolStatus: "OK" | "DEGRADED" | "FAILED" | "SKIPPED";
        /**
         * ValidateResponse
         * @description ``POST /v1/validate`` 200 body (API_CONTRACT §4.5). No tools run, no GPU touched.
         */
        ValidateResponse: {
            /** Inputs */
            inputs: components["schemas"]["InputManifest"][];
            compatibility: components["schemas"]["CompatibilityReport"];
            /**
             * Supported Tasks
             * @description Capability matching over the registry — lets the UI grey out impossible questions.
             */
            supported_tasks: components["schemas"]["TaskType"][];
            /** Warnings */
            warnings?: components["schemas"]["WarningItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WarningItem
         * @description A non-fatal condition worth surfacing to the user.
         */
        WarningItem: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Ref
             * @description img_*, art_* or None.
             */
            ref?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    registry_v1_registry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistryResponse"];
                };
            };
        };
    };
    validate_v1_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validate_v1_validate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_v1_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_v1_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job_v1_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. Event order is guaranteed: queued -> stage -> plan -> interleaved step_started/step_completed/artifact -> answer_delta* -> done|error. `done` and `error` are terminal and mutually exclusive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Unknown or evicted job. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_v1_artifacts__trace_id___artifact_id___ext__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
                artifact_id: string;
                ext: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/geo+json": unknown;
                    "application/json": unknown;
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/tiff": unknown;
                };
            };
            /** @description Not modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown trace or artifact */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The trace has been evicted */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_v1_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTrace"];
                };
            };
            /** @description Unknown trace. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
