"""Frozen Pydantic v2 schemas for the SatQuery AI API contract (schema_version 1.0)."""

from satquery.schemas.api import (
    AnalyzeOptions,
    AnalyzeResponse,
    ApiError,
    ApiErrorResponse,
    DeviceInfo,
    HealthResponse,
    ModelInfo,
    RegistryResponse,
    ValidateResponse,
)
from satquery.schemas.compatibility import CheckResult, CommonGrid, CompatibilityReport
from satquery.schemas.enums import (
    ArtifactType,
    CheckName,
    CheckStatus,
    Device,
    HealthStatus,
    ImageRole,
    Modality,
    Overall,
    PairType,
    PairTypeSource,
    Resampling,
    TaskType,
    ToolCategory,
    ToolStatus,
)
from satquery.schemas.manifest import InputManifest
from satquery.schemas.tool import Execution, InputContract, PlanStep, ToolSpec
from satquery.schemas.trace import (
    Answer,
    ArtifactGeo,
    ArtifactRef,
    AuditTrace,
    Citation,
    Confidence,
    ErrorItem,
    Plan,
    QuerySpec,
    ResolvedTask,
    WarningItem,
)
from satquery.schemas.version import SCHEMA_VERSION

__all__ = [
    "SCHEMA_VERSION",
    "AnalyzeOptions",
    "AnalyzeResponse",
    "Answer",
    "ApiError",
    "ApiErrorResponse",
    "ArtifactGeo",
    "ArtifactRef",
    "ArtifactType",
    "AuditTrace",
    "CheckName",
    "CheckResult",
    "CheckStatus",
    "Citation",
    "CommonGrid",
    "CompatibilityReport",
    "Confidence",
    "Device",
    "DeviceInfo",
    "ErrorItem",
    "Execution",
    "HealthResponse",
    "HealthStatus",
    "ImageRole",
    "InputContract",
    "InputManifest",
    "Modality",
    "ModelInfo",
    "Overall",
    "PairType",
    "PairTypeSource",
    "Plan",
    "PlanStep",
    "QuerySpec",
    "RegistryResponse",
    "Resampling",
    "ResolvedTask",
    "TaskType",
    "ToolCategory",
    "ToolSpec",
    "ToolStatus",
    "ValidateResponse",
    "WarningItem",
]
